// Writes the link-preview block into every page listed in cards.mjs.
//
// Everything here is derived, nothing is typed twice: the title, description
// and alt text come from cards.mjs, and the width and height are read out of
// the PNG's own header rather than trusted. tests/og-cards.test.mjs checks that
// the declared dimensions match the file, so a card regenerated at a different
// size fails the build instead of rendering cropped in someone's feed.
//
// Re-running is safe: the previous block is removed before the new one goes in.
//
// Run: node apply-meta.mjs [--check]     (--check writes nothing, reports drift)
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cards } from './cards.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const siteDir = join(here, '..', '..', 'site');
const BASE = 'https://tools.quotebot.io';
const check = process.argv.includes('--check');

// The scrapers cache hard once they have fetched an image, so a changed picture
// needs a changed filename, not just new bytes at the same path. Worth knowing
// before wondering why a preview is stale.
const NOTE = `<!--
  Link preview card. Generated by tools/og/apply-meta.mjs from tools/og/cards.mjs
  -- edit the copy there and re-run, do not hand-edit these tags.

  og:image is absolute because the scrapers fetch it from their own servers,
  where a relative path resolves against nothing. It is cached hard once
  fetched, so a changed picture needs a changed FILENAME.
-->`;

const esc = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// PNG: 8-byte signature, then the IHDR chunk, whose data starts at byte 16.
function pngSize(file) {
  const b = readFileSync(file);
  if (b.readUInt32BE(0) !== 0x89504e47) throw new Error(`${file} is not a PNG`);
  return { width: b.readUInt32BE(16), height: b.readUInt32BE(20) };
}

function block(card) {
  const url = `${BASE}/${card.page}`;
  const img = `${BASE}/og/${card.file}`;
  const { width, height } = pngSize(join(siteDir, 'og', card.file));
  const t = esc(card.title);
  const d = esc(card.description);
  const a = esc(card.alt);
  return [
    NOTE,
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="Quote-Bot">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${t}">`,
    `<meta property="og:description" content="${d}">`,
    `<meta property="og:image" content="${img}">`,
    `<meta property="og:image:secure_url" content="${img}">`,
    `<meta property="og:image:type" content="image/png">`,
    `<meta property="og:image:width" content="${width}">`,
    `<meta property="og:image:height" content="${height}">`,
    `<meta property="og:image:alt" content="${a}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${t}">`,
    `<meta name="twitter:description" content="${d}">`,
    `<meta name="twitter:image" content="${img}">`,
    `<meta name="twitter:image:alt" content="${a}">`,
  ].join('\n');
}

// Take out whatever is there now -- our own generated comment, the hand-written
// one on quotetool.html, and any og:/twitter: meta line -- so re-running
// replaces rather than stacks.
function strip(html) {
  return html
    .replace(/<!--\s*\n\s*Link preview card\.[\s\S]*?-->\n?/g, '')
    .replace(/^[ \t]*<meta\s+(?:property="og:|name="twitter:)[^>]*>\n?/gim, '');
}

// Sit the block where quotetool.html already has it: after the canonical link,
// or failing that after the description, or failing that after the title.
function insert(html, text) {
  for (const re of [
    /<link\s+rel="canonical"[^>]*>/i,
    /<meta\s+name="description"[^>]*>/i,
    /<\/title>/i,
  ]) {
    const m = html.match(re);
    if (m) {
      const at = m.index + m[0].length;
      // Swallow whatever blank lines the strip left behind, so running this
      // twice produces the same file rather than a growing gap.
      const rest = html.slice(at).replace(/^\n+/, '');
      return html.slice(0, at) + '\n\n' + text + '\n' + rest;
    }
  }
  throw new Error('no anchor found in <head>');
}

let changed = 0;
for (const card of cards) {
  const file = join(siteDir, card.page);
  const before = readFileSync(file, 'utf8');
  const after = insert(strip(before), block(card));
  if (after === before) {
    console.log(`  ${card.page.padEnd(38)} unchanged`);
    continue;
  }
  changed++;
  if (check) {
    console.log(`  ${card.page.padEnd(38)} WOULD CHANGE`);
  } else {
    writeFileSync(file, after);
    console.log(`  ${card.page.padEnd(38)} ${card.file}`);
  }
}
console.log(check ? `${changed} page(s) would change` : `${changed} page(s) written`);
if (check && changed) process.exitCode = 1;
